#!/bin/sh

[ $# -ne 2 ] && {
	printf "usage: $0 what where" 1>&2
	exit 1
}

child="$1"
where="$2"

total=$(git -C "$child" rev-list --count HEAD)
finished=0

for commit in $(git -C "$child" rev-list --reverse HEAD)
do
	# copy the commit from the child to the parent
	git -C "$child" cat-file commit "$commit" | git hash-object -t commit -w --stdin > /dev/null

	# copy the tree from the child to the parent
	treehash=$(git -C "$child" cat-file -p $commit | head -n1 | cut -f2 -d' ')

	git -C "$child" cat-file tree "$treehash" | git hash-object -t tree -w --stdin > /dev/null

	# copy the files and subtrees into the parent
	git -C "$child" diff-tree -m --root -t "$commit" | while read line
	do
		newhash=$(echo "$line" | cut -d' ' -f4)
		[ "$newhash" = "0000000000000000000000000000000000000000" ] && continue
		type=$(git -C "$child" cat-file -t "$newhash")
		[ "$type" = "commit" ] && continue

		git -C "$child" cat-file "$type" "$newhash" | git hash-object -t "$type" -w --stdin > /dev/null
	done

	git rm -q -r --cached "$where"
	git read-tree --prefix="$where" "$treehash"

	git commit --allow-empty -C "$commit"

	finished=$(( finished + 1 ))
	printf "%s/%s finished\n" "$finished" "$total"
done
