#!/bin/sh

[ $# -ne 2 ] && {
	printf "usage: $0 path_to_child subdir_in_parent" 1>&2
	exit 1
}

if git diff-files --quiet || git diff-index --quiet --cached HEAD --
then
	printf "Changes in the index or working tree will be lost. Continue? [y/n]: "
    read yn
    case $yn in
        [Yy]*) ;;
        *) printf "No changes were made\n"; exit 1 ;;
    esac
fi

child="$1"
where="$2"

# pull the child's objects into the parent
git fetch "$child"

total=$(git rev-list --count FETCH_HEAD)
finished=0

for commit in $(git rev-list --reverse FETCH_HEAD)
do
	# read tree of new commit into index
	git read-tree --prefix="$where" "$commit"
	git commit --allow-empty -C "$commit"
	git rm -q -r --cached "$where"

	finished=$(( finished + 1 ))
	printf "%s/%s finished\n" "$finished" "$total"
done

# force worktree to reflect updated HEAD
git checkout -f HEAD
